# Generated by Django 3.1.1 on 2020-09-14 13:01

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20200914_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='country',
            field=django_countries.fields.CountryField(default='GH', max_length=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pricing',
            field=models.CharField(blank=True, choices=[('F', 'Free'), ('CP', 'CUSTOM PRICE')], default='F', max_length=2, null=True),
        ),
    ]
