# Generated by Django 3.1.1 on 2020-09-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200914_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicImages',
            new_name='ClinicImage',
        ),
        migrations.RenameModel(
            old_name='Memberships',
            new_name='Membership',
        ),
        migrations.RenameModel(
            old_name='Registrations',
            new_name='Registration',
        ),
    ]
